#ifndef NFRAMELESSWIDGET_GLOBAL_H
#define NFRAMELESSWIDGET_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(NFRAMELESSWIDGET_LIBRARY)
#  define NFRAMELESSWIDGET_EXPORT Q_DECL_EXPORT
#else
#  define NFRAMELESSWIDGET_EXPORT Q_DECL_IMPORT
#endif

#endif // NFRAMELESSWIDGET_GLOBAL_H
